package jwt_scopes

const (
	_ = 1 << iota

	//USERS
	ACCOUNT_READ //for reading account data,
	ACCOUNT_WRITE
	ACCOUNT_MASTER
	ACCOUNT_SUB

	//OOB
	OOB_USER_PASSWORD_CHANGE
	OOB_USER_EMAIL_CHANGE
	OOB_USER_ACTIVATE

	//OAUTH
	OAUTH_STATE

	//TRANSACTIONS
	TRANSACTION_PAYMENT
)

const ACCOUNT_FULL_ANY = ACCOUNT_READ | ACCOUNT_WRITE
const ACCOUNT_FULL_MASTER = ACCOUNT_READ | ACCOUNT_WRITE | ACCOUNT_MASTER
const ACCOUNT_FULL_SUB = ACCOUNT_READ | ACCOUNT_WRITE | ACCOUNT_SUB
